"""Out-of-domain extrapolation study for the surrogate.

Evaluates the already-trained per-archetype surrogates on designs sampled in a
shell *outside* the training box (generated by scripts/exportExtrapolation.ts at
several shell widths delta). Reports, per archetype and per shell:

  * accuracy (MAPE, R2) on the genuine-failure designs, against the in-domain
    held-out test split, so the degradation with distance from the training box
    is explicit; and
  * the bagged-ensemble spread sigma, and the fraction of out-of-domain designs
    a domain-of-validity flag catches -- sigma exceeding the 95th percentile of
    the in-domain test spread -- which should rise with the shell width.

Out-of-domain inputs are standardised with the *training* mean/std (the
surrogate's own normalisation), never their own statistics.

Run (after models + ensembles exist):
    python extrapolation.py
"""
from __future__ import annotations

import json
import os
from collections import Counter

import numpy as np
import torch

from config import get_config
from data import load_archetype, load_json
from model import STMNet

ARCHS = ["deepBeam", "hammerhead", "multiColumnBent", "pileCap"]
DELTAS = [0.1, 0.2, 0.3]
EXTRAP_PATH = "../data/dataset_extrap_{delta}.json.gz"
FLAG_PCTL = 95.0   # in-domain sigma percentile defining the domain-of-validity flag


def _topology_sig(d: dict) -> tuple:
    return (tuple(n["id"] for n in d["truss"]["nodes"]),
            tuple((m["id"], m["ni"], m["nj"]) for m in d["truss"]["members"]))


def dominant_sig(designs: list[dict]) -> tuple:
    return Counter(_topology_sig(d) for d in designs).most_common(1)[0][0]


def stats(pred: np.ndarray, true: np.ndarray) -> tuple[float, float, float]:
    err = pred - true
    rmse = float(np.sqrt((err ** 2).mean()))
    mape = float((np.abs(err) / np.clip(true, 1e-6, None)).mean() * 100.0)
    ss_tot = ((true - true.mean()) ** 2).sum()
    r2 = float(1.0 - (err ** 2).sum() / max(ss_tot, 1e-12))
    return mape, rmse, r2


def load_models(arch: str, theta_dim: int, n_members: int, cfg) -> tuple:
    """Return (single model, list of ensemble members)."""
    single = STMNet(theta_dim, n_members, cfg)
    ckpt = torch.load(os.path.join(cfg.out_dir, arch, "model.pt"),
                      map_location="cpu", weights_only=False)
    single.load_state_dict(ckpt["state_dict"])
    single.eval()

    members = []
    ens_dir = os.path.join(cfg.out_dir, arch, "ensemble")
    if os.path.isdir(ens_dir):
        for f in sorted(os.listdir(ens_dir)):
            if f.endswith(".pt"):
                m = STMNet(theta_dim, n_members, cfg)
                m.load_state_dict(torch.load(os.path.join(ens_dir, f),
                                             map_location="cpu",
                                             weights_only=False)["state_dict"])
                m.eval()
                members.append(m)
    return single, members


def ensemble_std(members: list[STMNet], theta: torch.Tensor) -> np.ndarray:
    with torch.no_grad():
        preds = np.stack([np.asarray(m(theta)[0].tolist(), dtype=float)
                          for m in members])
    return preds.std(0, ddof=1)


def parse_extrap(path: str, arch: str, theta_keys: list[str], sig: tuple,
                 mean: np.ndarray, std: np.ndarray) -> tuple:
    """Return (theta_norm [n, d], lambda_f [n]) for topology-matching designs."""
    raw = load_json(path)["designs"]
    keep = [d for d in raw if d["archetype"] == arch and _topology_sig(d) == sig]
    theta = np.array([[d["params"][k] for k in theta_keys] for d in keep],
                     dtype=np.float32)
    lam = np.array([d["labels"]["failureLoadFactor"] for d in keep],
                   dtype=np.float32)
    theta_n = (theta - mean) / std
    return torch.tensor(theta_n), lam, len(keep), len(raw)


def main() -> None:
    print(f"{'archetype':16s} {'set':>10s} {'n':>5s} {'MAPE%':>7s} "
          f"{'R2':>7s} {'mean_sig':>9s} {'flagged%':>9s}")
    summary = {}
    for arch in ARCHS:
        cfg = get_config(archetype=arch)
        data = load_archetype(cfg)
        theta_keys = data.theta_keys
        mean = data.theta_mean.numpy()
        std = data.theta_std.numpy()
        single, members = load_models(arch, len(theta_keys), data.n_members, cfg)

        # in-domain reference: held-out test split, genuine failures
        te = data.test_idx
        with torch.no_grad():
            id_pred = single(data.theta[te])[0].numpy()
        id_true = data.lambda_f[te].numpy()
        id_gen = id_true < cfg.lambda_max - 1e-3
        id_sig = ensemble_std(members, data.theta[te]) if members else None
        tau = (np.percentile(id_sig[id_gen], FLAG_PCTL)
               if id_sig is not None else float("nan"))
        id_flag = (float(np.mean(id_sig[id_gen] > tau)) * 100
                   if id_sig is not None else float("nan"))
        mape, _, r2 = stats(id_pred[id_gen], id_true[id_gen])
        ms = float(id_sig[id_gen].mean()) if id_sig is not None else float("nan")
        print(f"{arch:16s} {'in-domain':>10s} {int(id_gen.sum()):5d} "
              f"{mape:7.2f} {r2:7.3f} {ms:9.4f} {id_flag:9.1f}")
        summary[arch] = {"in_domain": (mape, r2, ms), "tau": tau, "shells": {}}

        sig = dominant_sig([d for d in load_raw(cfg) if d["archetype"] == arch])
        for delta in DELTAS:
            path = EXTRAP_PATH.format(delta=delta)
            theta_n, lam, n_match, n_tot = parse_extrap(
                path, arch, theta_keys, sig, mean, std)
            with torch.no_grad():
                pred = single(theta_n)[0].numpy()
            gen = lam < cfg.lambda_max - 1e-3
            sig_e = ensemble_std(members, theta_n) if members else None
            flagged = (float(np.mean(sig_e[gen] > tau)) * 100
                       if sig_e is not None else float("nan"))
            mape, _, r2 = stats(pred[gen], lam[gen])
            mse = float(sig_e[gen].mean()) if sig_e is not None else float("nan")
            print(f"{arch:16s} {('delta='+str(delta)):>10s} {int(gen.sum()):5d} "
                  f"{mape:7.2f} {r2:7.3f} {mse:9.4f} {flagged:9.1f}")
            summary[arch]["shells"][delta] = {
                "n_match": n_match, "n_tot": n_tot, "n_gen": int(gen.sum()),
                "mape": mape, "r2": r2, "mean_sig": mse, "flagged": flagged}
        print()

    os.makedirs("runs", exist_ok=True)
    json.dump(summary, open("runs/extrapolation_summary.json", "w"), indent=2)
    print("wrote runs/extrapolation_summary.json")


def load_raw(cfg) -> list[dict]:
    return load_json(cfg.dataset_path)["designs"]


if __name__ == "__main__":
    main()
